lib/hydra/derivatives.rb, lib/hydra/derivatives/video.rb, lib/hydra/derivatives/video/config.rb, lib/hydra/derivatives/video/processor.rb, spec/units/video_spec.rb
=> Video processor should be configurable

README.md
There seem to be a bunch of new configuration options that are undocumented.  These are the ones that I have used.
=> Adding some of the new configuration options to the readme.

hydra-derivatives.gemspec, lib/hydra/derivatives.rb, lib/hydra/derivatives/document.rb, lib/hydra/derivatives/extract_metadata.rb, lib/hydra/derivatives/jpeg2k_image.rb, lib/hydra/derivatives/shell_based_processor.rb, lib/hydra/derivatives/tempfile_service.rb, spec/lib/hydra/derivatives/extract_metadata_spec.rb, spec/services/tempfile_service_spec.rb
rather than requiring the ExtractMetadata mixin to provide one
=> Tempfile service provides a tempfile

lib/hydra/derivatives.rb, spec/units/derivatives_spec.rb
This will help out projecthydra-labs/hydra-works#105 making it easier to integrate.
=> Specify a custom processor class, ref #55

Gemfile, spec/services/retrieve_source_file_service_spec.rb, spec/units/processor_spec.rb
=> Output file service test coverage

README.md
Specify the version required for fits. This may change based on https://github.com/projecthydra-labs/hydra-works/pull/199
=> fits version specified

README.md, lib/hydra/derivatives/image.rb, lib/hydra/derivatives/jpeg2k_image.rb, lib/hydra/derivatives/processor.rb, lib/hydra/derivatives/shell_based_processor.rb, spec/units/image_spec.rb, spec/units/transcoding_spec.rb, spec/units/video_spec.rb
Avoid calling deprecated methods
=> Rename the :datastream option to :output_path

lib/hydra/derivatives/processors/jpeg2k_image.rb
Fixes Jpeg2k Processor. Closes #94.
=> Silence Kakadu messages.

lib/hydra/derivatives/processors/image.rb, spec/processors/image_spec.rb
Refactors Hydra::Derivatives::Processors::Image while fixing the outstanding issue.
=> Flatten images when resizing, fixes #110

.rubocop.yml, spec/processors/full_text_spec.rb
This file wasn't named correctly, so it was never actually running. Now that it is, I've refactored it and hopefully made the assertions it's testing a bit clearer.
=> Enabling full text spec test

Gemfile, spec/spec_helper.rb
=> Turn on coveralls

spec/units/transcoding_spec.rb
This branch is based on #142 so it should get merged after it.
=> Fix most transcoding tests

.rubocop.yml, lib/hydra/derivatives/processors/active_encode.rb, spec/processors/active_encode_spec.rb
Part of this story:
https://github.com/avalonmediasystem/avalon/issues/1785
Ping @csyversen & @bkeese for review
=> If encoding failed, raise an exception

.rubocop.yml, lib/hydra/derivatives.rb, lib/hydra/derivatives/processors/active_encode.rb, lib/hydra/derivatives/runners/active_encode_derivatives.rb, spec/processors/active_encode_spec.rb
Here are some notes about how to run an encoding job on AWS.  We can add some similar notes on the `active_encode_dev_con` branch once we're finished with the code and the branch is ready to merge into master.
https://github.com/curationexperts/active-encode-demo/blob/master/doc/transcoding_with_amazon.md
=> Wait for encode to finish. Part of avalonmediasystem/avalon#1827

README.md, doc/amazon_elastic_transcoder.md
I know we aren't fully done with the code, so these instructions might change a bit, but I wanted to write the first draft of the documentation.
=> Add documentation about how to use Amazon encoding service. Part of story avalonmediasystem/avalon#1785

hydra-derivatives.gemspec, lib/hydra/derivatives/services/persist_basic_contained_output_file_service.rb, spec/processors/full_text_spec.rb, spec/services/persist_basic_contained_output_file_service_spec.rb
=> Store the character encoding from full text extraction

lib/hydra/derivatives/io_decorator.rb, lib/hydra/derivatives/services/persist_basic_contained_output_file_service.rb, lib/hydra/derivatives/services/persist_output_file_service.rb, spec/units/io_decorator_spec.rb
This matches the interface provided by
ActionDispatch::HTTP::UploadedFile
=> Rename IoDecorator#original_name to #original_filename

lib/hydra/derivatives/processors/full_text.rb, spec/processors/full_text_spec.rb
Hope this is acceptable! 🤞 
PS: I emailed my iCLA last week to legal@samvera.org
=> added ssl check to turn on use_ssl on req object; plus specs

lib/hydra/derivatives/processors/full_text.rb, spec/processors/full_text_spec.rb
If Solr is using basic auth and the url is supplied in the form `user:pass@solr_url` the full text extraction will fail with a 401 Unauthorized.
This PR adds support for basic auth when calling the full text extraction service.
=> Support basic auth in solr extract service

CODE_OF_CONDUCT.md, CONTRIBUTING.md, README.md, SUPPORT.md
- Resolve #187; update contributing guidelines
- Resolve #188; update help information
=> Update docs to use templates

.circleci/config.yml
This uses some shared configuration we're trying out at
https://github.com/samvera-labs/samvera-circleci-orb
=> Use CircleCI Orb

README.md
=> Change README badge to CircleCI

lib/hydra/derivatives/logger.rb, lib/hydra/derivatives/processors/processor.rb, spec/processors/processor_spec.rb, spec/processors/video_spec.rb, spec/runners/runner_spec.rb, spec/services/persist_output_file_service_spec.rb, spec/services/tempfile_service_spec.rb, spec/spec_helper.rb, spec/units/audio_encoder_spec.rb, spec/units/logger_spec.rb
This found a couple bugs in the code, and also sets the minimum allowed coverage to be 100%.
=> 100% Coverage

.circleci/config.yml
Re: https://github.com/samvera/maintenance/issues/20
=> Update Circle CI Ruby Versions; 2.4.6, 2.6.3

.circleci/config.yml
=> Adds Ruby 2.7 releases to the CircleCI configuration

.circleci/config.yml, .rubocop.yml, Gemfile, Rakefile, hydra-derivatives.gemspec, spec/processors/document_spec.rb, spec/processors/full_text_spec.rb, spec/spec_helper.rb
This blocks https://github.com/samvera/hydra-works/pull/375
=> Updating activesupport to support Rails 6.x releases

.circleci/config.yml, README.md, hydra-derivatives.gemspec, lib/hydra/derivatives/processors/image.rb, spec/processors/image_spec.rb
This is more efficient and appears to fix https://github.com/samvera/hyrax/issues/4971 with both ImageMagick 6 and 7.
=> Combine flatten and resize operations

.circleci/config.yml
=> Adding the CircleCI configuration for nightly test suite executions

lib/hydra/derivatives/processors/video/config.rb, lib/hydra/derivatives/processors/video/processor.rb, spec/processors/video_spec.rb
This changes allow to set video resolution and bitrate for video derivatives
=> adding control to video parameters

CONTRIBUTING.md, README.md
This is necessary in order to request from the community renewed efforts for maintenance, and to direct those outside of the community to the Samvera Slack.
=> Updating the Product Owner information in preparation for the 2022 autumn request for maintenance

.circleci/config.yml, hydra-derivatives.gemspec
Do we need to add tests for different rails versions?
=> Test on newer ruby and rails versions

README.md
=> Updating the Product Owner to stkenny

Gemfile, hydra-derivatives.gemspec
This will allow applications to use sprockets 4
=> Update gemspec to active_encode 1.2 and remove sprockets from Gemfile

.circleci/config.yml, hydra-derivatives.gemspec
I think this just needs a compatible release of AF.
=> Relax rails version.

.circleci/config.yml, hydra-derivatives.gemspec
Drop unsupported versions of ruby.
=> Test with latest ruby and rails versions
