samvera/hydra-derivatives

- lib/hydra/derivatives.rb
transform_datastream, to not pass a default options values,
since the method def for transform_file already sets the
default values.
> change call to transform_file, in the deprecated method. Fixes #58

- lib/hydra/derivatives/shell_based_processor.rb
- spec/units/transcoding_spec.rb
and the process can terminate. Previously it was blocking on stderr.read, while stdout was ready to be read, but wasn't being read.
> Use IO.select so that all buffers get read

- lib/hydra/derivatives/processors/image.rb
- spec/processors/image_spec.rb
The quality param in http://www.imagemagick.org/script/command-line-options.php#quality allows setting of image compression. The hydra-derivatives derivatives/image.rb code was previously accepting/passing it only through protected methods.
This pull request allows it to be passed in by the user when declaring the directives.
> make quality be passed when creating an image

- lib/hydra/derivatives/processors/document.rb
- spec/processors/document_spec.rb
- spec/units/transcoding_spec.rb
This improves the function of Hydra::Derivatives::Processors::Document and refactors its tests.
* correctly converts documents to pdf and other non-image formats
* jpg conversion is delegated to Hydra::Derivatives::Processors::Image so files are correctly resized
* adds additional units tests; refactors existing tests
> Convert documents to pdf and jpg, fixes #109

- lib/hydra/derivatives/processors/image.rb
- spec/processors/image_spec.rb
Flattening images in 9df9746fb91c00b5cce8305f6a990a67fbd34d43 created a new problem with multi-page pdf files. When creating thumbnails for these files, the resulting image has all of the pages layered one on top of the other instead of just the first page.
Since we need to keep the `flatten` option so that a pdf's background is retained properly, I decided to add a `layer` directive so that the user can decide which layer to choose. This also allows for additional tweaking should there be other multi-layer formats and the user needs to select a specific layer for derivative creation.
> Directive option for layer

- lib/hydra/derivatives/processors/image.rb
- spec/processors/image_spec.rb
One last tweak, I hope.
For the PDF thumbnail generation to be effective, users would need to add the `layer: 0` directive to their application code, so instead let's just default it to the first layer if we're coming from a pdf. This also fixes another problem with thumbnails of office documents. Because we're passing a pdf to the image converter internally when we convert office documents to images, we won't need to specify a layer directive there either.
Alternatively, we could pass a layer directive to the image processor from the document processor, and leave the existing image processor code unchanged, but that would still leave existing implementations with the task of overriding their `create_derivatives` methods to pass that layer directive in for all their other pdfs.
This PR …
> Default to first page for pdf images

- README.md
The Processors namespace was created in this commit: https://github.com/projecthydra/hydra-derivatives/commit/4e0cff7c500227fff672cb0af88ed7d864f43820
Unfortunately that causes the examples in the readme to throw an error:
```
uninitialized constant Hyra::Derivatives::Video (NameError)
```
> Adding Processors namespace into readme so that the examples in the readme work

- .travis.yml
This test suite runs in less than a minute, we can afford to flesh out the build matrix for better coverage and earlier detection of deprecations.
> Expand build matrix

- spec/services/audio_derivatives_spec.rb
If your fedora config doesn't match that path, the code that converts URI to ID doesn't properly strip the URI, and you end up with duplicate path in your URI.
> Fixed a spec that might be broken, depending on your fedora config

- .gitignore
- lib/hydra/derivatives/processors/jpeg2k_image.rb
- spec/processors/jpeg2k_spec.rb
- spec/units/transcoding_spec.rb
Fixes #118 by un-protecting some class methods that were originally not actually protected, but then made protected by rubocop. Specs for these methods coming shortly...
.jp2 derivatives tests were still broken due to .txt being used as a default mime-type and extension, so that is explicitly set now.
> Fix failing test for creation of JPEG2000 derivatives.

- lib/hydra/derivatives.rb
- lib/hydra/derivatives/audio_encoder.rb
- lib/hydra/derivatives/processors/video/config.rb
- lib/hydra/derivatives/services/capability_service.rb
- spec/units/audio_encoder_spec.rb
This adds a service to check ffmpeg installed codecs for FDK. If you don't have that it will 
use the default AAC encoder in ffmpeg.
> Add a service to check ffmepg installed codecs

- spec/units/transcoding_spec.rb
Fixes failures when running https://github.com/projecthydra/hydra-derivatives/blob/master/spec/units/transcoding_spec.rb#L104 for attaching RAW image derivatives.
Closes #145 
I had to run `brew install ufraw` for RAW file processing support in ImageMagick to fix the following error:
```
Failure/Error: MiniMagick::Image.open(source_path)
MiniMagick::Invalid:
`identify /var/folders/3q/6phb_54d571483_gf73qdk2cfwtt1d/T/mini_magick20170403-56719-ypwzbc.dng` failed with error:
identify: delegate failed `'ufraw-batch' --silent --create-id=also --out-type=png --out-depth=16 '--output=%u.png' '%i'' @ error/delegate.c/InvokeDelegate/1845.
```
After installing ufraw, the changes in this PR fix these errors:
```
Failure/Error: uri = URI(directives.fetch(:url))
KeyError:
key not found: :url
```
``` …
```
> Fix 'attach RAW image' specs

- README.md
Without ufraw installed, this spec will fail:
"Transcoding with an attached RAW image transcodes".
> Added ufraw to the list of dependencies.

- README.md
Ghostscript is now a needed dependency on Hydra Derivatives to get the test suite passing with regard to the pdf tests.  This may have been missed since folks has Ghostscript installed due to Sufia/Hyrax work.
> ghostscript is a needed depenency

- .rubocop.yml
- lib/hydra/derivatives/processors/active_encode.rb
- lib/hydra/derivatives/services/uri_source_file_service.rb
- spec/processors/active_encode_spec.rb
Part of story avalonmediasystem/avalon#1785
> Handle the case where active_encode returns a 'cancelled' status

- lib/hydra/derivatives/processors/active_encode.rb
- spec/processors/active_encode_spec.rb
Because I'm submitting 2 PRs in a row against the same branch, the diff for this PR will also include the changes for PR #150 until PR #150 gets merged.
The true diff for this PR is quite small.  You can see it here:
https://github.com/projecthydra/hydra-derivatives/compare/cancelled_status...add_filename_to_error_message
Please merge PR #150 before this one.  Thanks!
> Add filename to error message

- .rubocop.yml
- lib/hydra/derivatives/processors/active_encode.rb
- spec/processors/active_encode_spec.rb
This PR is meant to address this comment by @mjgiarlo in a previous PR:
https://github.com/projecthydra/hydra-derivatives/pull/154#issuecomment-295462717
The situation that this code is trying to handle:
If a Timeout error is raised, we try to clean up our resources by cancelling the encoding.  If an exception is raised during the cleanup, we don't want the original Timeout error to be lost.
The current solution:
The way I have done it here is to rescue any error and re-raise the Timeout error with the new error message appended to it.
@mjgiarlo Do you think it's sufficient to tack the 2nd error message onto the first Timeout error, no matter what type of error was raised?  Or do you think it's better to pursue the goal of rescuing specific errors?  Can you think of a nicer way to raise a …
> Preserve the 2nd error message in the case where an error is raised during the cleanup after a timeout error.

- lib/hydra/derivatives.rb
- lib/hydra/derivatives/processors/active_encode.rb
- lib/hydra/derivatives/runners/active_encode_derivatives.rb
- lib/hydra/derivatives/services/null_output_file_service.rb
- lib/hydra/derivatives/services/persist_external_file_output_file_service.rb
- spec/processors/active_encode_spec.rb
- spec/runners/active_encode_derivatives_spec.rb
- spec/services/persist_external_file_output_file_service_spec.rb
The PersistExternalFileOutputFileService has a slightly different interface than the other output file services.  It takes a hash of information about the output file created through ActiveEncode instead of an open File object or String.  I left a TODO to update the code for when projecthydra/active_fedora#1234 gets merged.
> Persist active encode results in ActiveFedora::File objects with external content

- lib/hydra/derivatives/processors/document.rb
- lib/hydra/derivatives/processors/ffmpeg.rb
- lib/hydra/derivatives/processors/jpeg2k_image.rb
Fix for #163 
Quote the file path to prevent a bash syntax error.
> Quote file path in soffice command.

- .rubocop.yml
- README.md
- doc/amazon_elastic_transcoder.md
- hydra-derivatives.gemspec
- lib/hydra/derivatives.rb
- lib/hydra/derivatives/config.rb
- lib/hydra/derivatives/processors.rb
- lib/hydra/derivatives/processors/active_encode.rb
- lib/hydra/derivatives/runners/active_encode_derivatives.rb
- lib/hydra/derivatives/services/persist_external_file_output_file_service.rb
- lib/hydra/derivatives/services/remote_source_file.rb
- spec/processors/active_encode_spec.rb
- spec/runners/active_encode_derivatives_spec.rb
- spec/services/persist_external_file_output_file_service_spec.rb
- spec/services/remote_source_file_spec.rb
- spec/units/config_spec.rb
- spec/units/derivatives_spec.rb
The ActiveEncode runner allows using [ActiveEncode](https://github.com/projecthydra-labs/active_encode) within hydra-derivatives to generate derivatives using the adapters supported by ActiveEncode.  Currently Amazon Elastic Transcoder is the only production ready adapter available but prototypes exist for zencoder and [shingoncoder](https://github.com/jcoyne/shingoncoder) (FFmpeg through ActiveJob).  The key differences between ActiveEncode and hydra-derivatives are:
- ActiveEncode can produce multiple derivatives of potentially different formats (video derivatives, thumbnail images) from a single invocation
- ActiveEncode does not necessarily operate on local files
- ActiveEncode returns a url to the derivatives it creates and not a bitstream
- ActiveEncode allows for polling to get …
> Add active_encode support to hydra-derivatives

- lib/hydra/derivatives/processors/full_text.rb
- spec/processors/full_text_spec.rb
Previously we were using the value of the yaml configuration, which is
the default way to initialize a connection, but not the only way. It is
also possible for the connection to be initialized programatically.
This is what hyku is doing to support multiple tenants each with their
own solr collection.
See https://github.com/samvera-labs/hyku/issues/1275
> Use activeFedora current solr connection for the extract uri

- lib/hydra/derivatives/processors/full_text.rb
- spec/processors/full_text_spec.rb
Per https://bugs.ruby-lang.org/issues/2567, Net::HTTP has a known issue where `response.body` is always `ASCII-8BIT` encoded. The issue has been debated for almost 8 years now, with no resolution in sight. Since Faraday doesn't compensate for it, the only thing to do is use `force_encoding` if the `Content-Type|charset` subfield is present.
> Compensate for Net::HTTP disrespecting Content-Type encoding

- README.md
Based on conversations on Slack:
Person 1:
> I get from Readme of Hydra-derivatives but is not clear for my where
> can I put in my project
Person 2:
> I would guess and say in a config file, such as
> `/config/application.rb`, or narrow it down to `/config/environments`
> dev/test/prod etc. (edited)
>
> I suppose, another option is putting it inside an initializer just for hydra-derivatives.
Person 3
> I found a scholarsphere implementation https://github.com/psu-stewardship/scholarsphere/blob/master/config/initializers/hydra_derivatives_config.rb#L5
> However…I think Person 2's suggestion would also work (and allow for
> less antics if you want variation between environments).
> Amending documentation on configuration

- lib/hydra/derivatives/io_decorator.rb
Removing this broke backwards compat in 3.x series, and broke sufia 7/curation concerns 1.7 trying to new h-d 3.4. 
Restore the writer as deprecated, same as the #original_name reader is. Recommend 3.4.1 release with this.
Closes #181
Ref https://github.com/samvera/sufia/pull/3183
> restore original_name= to removed instead of deprecated

- .travis.yml
- hydra-derivatives.gemspec
This fixes test failures due to an old version of Ruby not being able to pull gems.  This also updates to newer Ruby versions so tests are running against the latest 2.x.x.
> Update list of Ruby versions for travis CI

- lib/hydra/derivatives/processors/shell_based_processor.rb
- spec/processors/shell_based_processor_spec.rb
Closes stderr and stdout at the end of the process, rather than never
closing stderr, and closing stdout before there's time for any data to
come in.  This fixes a crash when processes (like opj_compress) print
out to stdout a lot.
Fixes an edge case where an EOFError causes an invocation of a
non-existent "Rails.logger" function.  In Rails, it would be
Rails.logger.debug or something, and outside Rails contexts, there is no
Rails.logger at all.  This was never noticed before, as EOFs weren't
detected because the previous logic never checked stdout, since it was
already closed.
> Fix shell execution

- lib/hydra/derivatives/services/persist_output_file_service.rb
Stumbled across this typo while using this class; there's no open issue for it, but I can add one if that's the preferred workflow.
> Fix typo in default mime_type value

- README.md
Also proving that CI build works again now that kakadusoftware.com is back online.
Refs #202
> Small wording change in README

- lib/hydra/derivatives/processors/document.rb
- lib/hydra/derivatives/processors/full_text.rb
The Solr extract service started failing with `undefined method 'use_ssl=' for #<Net::HTTP::Post POST>` after updating hyrax from 2.5.1 to 2.6.0. This was using ruby 2.4.1 with rails 5.1.6.2. It looks like this commit was the culprit: [https://github.com/samvera/hydra-derivatives/commit/35a6e7165cec5ea9ccc43163454af6cbc4fd6053](https://github.com/samvera/hydra-derivatives/commit/35a6e7165cec5ea9ccc43163454af6cbc4fd6053). I pasted the full sidekiq error below.
It seems like the .use_ssl method should apply to `Net::HTTP.start`, not `Net::HTTP::Post` here: https://github.com/samvera/hydra-derivatives/blob/master/lib/hydra/derivatives/processors/full_text.rb#L37
Net::HTTP.start Docs: [https://ruby-doc.org/stdlib-2.6.5/libdoc/net/http/rdoc/Net/HTTP.html#method-i-use_ssl-3D](https://ruby-doc.or …
> Solr extract service now succeeds over SSL

- hydra-derivatives.gemspec
Removing the test_files from the gemspec ensures that consumers of the Gem are not required to download any fixture files with the Gem (please see samvera/hyrax#4245 for the origin discussion).
> Removing spec files from gem distribution

- .circleci/config.yml
- .rubocop.yml
- Gemfile
- README.md
- Rakefile
- hydra-derivatives.gemspec
- spec/processors/document_spec.rb
- spec/processors/full_text_spec.rb
- spec/spec_helper.rb
Supersedes #221 by removing active-fedora dependency pinning.
> Rails6 update

- hydra-derivatives.gemspec
Co-Authored-By: Anna Headley <anna.headley@gmail.com>
Co-Authored-By: Chris Colvard <chris.colvard@gmail.com>
Keeps compatibility with active-fedora 11 and 12 versions that pin the rdf-vocab gem.
> Allow active-fedora with pinned rdf-vocab

- README.md
- lib/hydra/derivatives/config.rb
- solr/config/xslt/example.xsl
- solr/config/xslt/luke.xsl
- spec/fixtures/jpeg2k_config.yml
- spec/processors/jpeg2k_spec.rb
The CSS changes aren't strictly necessary, but the other changes should resolve the recipe lookup issue (#218).
> Standardize 'gray' (rather than 'grey') across all instances

- .circleci/config.yml
Reverts to previous method of making kdu_compress available in CI, with an updated url and added caching of the archive.
> Install kdu_compress from official source

- .circleci/config.yml
- hydra-derivatives.gemspec
Now that there's a released AF version that supports 6.1, this should be
fine.
> Remove Rails 6.1 restriction

- .circleci/config.yml
Fixes #228
This PR adds the Circle CI step that fails if the branch name is master.
> Updating the CircleCI configuration to check for a master branch

- Gemfile
- spec/spec_helper.rb
Coveralls is breaking the CircleCI build for #252  and has been flakey for a long time now.  This PR proposes dropping coveralls like has been done in other samvera repos (e.g. https://github.com/samvera/browse-everything/pull/401).
> Remove coveralls

- lib/hydra/derivatives/processors/shell_based_processor.rb
- spec/processors/shell_based_processor_spec.rb
Fixes #251 
Adds handling of IO::WaitReadable errors (such as IO::EAGAINWaitReadable) in the manner suggested by IO#read_nonblock documentation. The existing use of IO.select appears able to fail when only one of stdout or stderr is ready. Each file will now be retried if the read is not ready.
> rescue IO::EAGAINWaitReadable errors

- lib/hydra/derivatives/processors/jpeg2k_image.rb
- spec/processors/jpeg2k_spec.rb
kdu_compress crashes with a negative Clevels value, but succeeds with a zero.
Resolves #217 
@jenlindner I _think_ this captures the approach you recommended?
> Ensure a nonnegative calculated Clevels value

- .circleci/config.yml
- lib/hydra/derivatives.rb
- lib/hydra/derivatives/processors/image.rb
- lib/hydra/derivatives/services/image_service.rb
- spec/processors/image_spec.rb
Attempting to contribute back our local support for graphicsmagick, which we have been using for about a year. It was originally added in this PR by @maxkadel :
https://github.com/UNC-Libraries/hy-c/pull/754
I was in the process of removing the imagemagick support from out local repo since we aren't using it at this point, but thought it would make sense to offer the double implementation back to the gem in case first in case its helpful.
* Adds a IMAGE_PROCESSOR environment variable which can be used to specify usage of imagemagick versus graphicsmagick for the image processor. 
* The new ImageService class handles the environment variable and default value
> Graphicsmagick support for image derivatives

- lib/hydra/derivatives/processors/video/config.rb
- spec/processors/video_spec.rb
I've detected that in the case of video derivatives, specifically with the .mp4 extension, if the source video has the yuv422p color profile, the derived video cannot be viewed on mobile phones. To solve this, it is proposed to force the conversion to yuv420p.
> add pix_fmt yuv420p to mp4 config
